import Foundation

// MARK: - Bazi

/// The Four Pillars of Destiny (四柱八字), representing a person's birth chart.
///
/// Bazi (八字, "Eight Characters") consists of four Ganzhi pillars derived from
/// the year, month, day, and hour of birth. It is the foundation of Chinese
/// fate calculation (命理學).
///
/// Example:
/// ```swift
/// let date = Date()
/// if let bazi = Bazi(date: date) {
///     print(bazi.description)
///     print("Day Master: \(bazi.dayMaster.chineseCharacter)")
///     print("Dominant element: \(bazi.dominantElement.chineseCharacter)")
/// }
/// ```
public struct Bazi: CustomStringConvertible, Equatable, Sendable {

  // MARK: Lifecycle

  /// Creates a Bazi from precomputed Ganzhi pillars.
  public init(nian: Ganzhi, yue: Ganzhi, ri: Ganzhi, shi: Ganzhi) {
    self.nian = nian
    self.yue = yue
    self.ri = ri
    self.shi = shi
  }

  /// Creates a Bazi from a `Date` using China Standard Time (UTC+8).
  ///
  /// Returns `nil` if the Ganzhi pillars cannot be computed for the given date.
  public init?(date: Date) {
    // Use the Chinese calendar for year/month pillars (nian/yue).
    let chineseCal = Calendar.chineseCalendarGTM8
    let chineseComponents = chineseCal.dateComponents(
      [.era, .year, .month, .day, .hour],
      from: date
    )
    // Use Gregorian calendar for day/hour pillars (ri/shi) since
    // the cycleIndex calculation in DateComponents+Day.swift requires
    // Gregorian year/month/day to compute a reference date.
    var gregorianCal = Calendar(identifier: .gregorian)
    gregorianCal.timeZone = TimeZone(secondsFromGMT: 8 * 3600)!
    let gregorianComponents = gregorianCal.dateComponents(
      [.year, .month, .day, .hour],
      from: date
    )
    guard
      let nianGanzhi = chineseComponents.nian,
      let yueGanzhi = chineseComponents.yue,
      let riGanzhi = gregorianComponents.riZhu,
      let shiGanzhi = gregorianComponents.shiZhu
    else {
      return nil
    }
    self.nian = nianGanzhi
    self.yue = yueGanzhi
    self.ri = riGanzhi
    self.shi = shiGanzhi
  }

  // MARK: Public

  /// The Year Pillar (年柱).
  public let nian: Ganzhi

  /// The Month Pillar (月柱).
  public let yue: Ganzhi

  /// The Day Pillar (日柱).
  public let ri: Ganzhi

  /// The Hour Pillar (時柱).
  public let shi: Ganzhi

  /// All four pillars in order: year, month, day, hour.
  public var pillars: [Ganzhi] { [nian, yue, ri, shi] }

  /// The Day Master (日主) — the Heavenly Stem of the day pillar.
  ///
  /// In Bazi analysis, the Day Master represents the self/person being analyzed.
  public var dayMaster: Tiangan { ri.gan }

  /// The Wuxing element of the Day Master.
  public var dayMasterElement: Wuxing { dayMaster.wuxing }

  /// All eight characters (stems and branches from all four pillars).
  public var allCharacters: [String] {
    pillars.flatMap { [$0.gan.chineseCharacter, $0.zhi.chineseCharacter] }
  }

  /// Count of each Wuxing element across all eight characters.
  public var elementCounts: [Wuxing: Int] {
    var counts: [Wuxing: Int] = [:]
    for pillar in pillars {
      counts[pillar.gan.wuxing, default: 0] += 1
      counts[pillar.zhi.wuxing, default: 0] += 1
    }
    return counts
  }

  /// The most frequently occurring Wuxing element in the chart.
  ///
  /// When there is a tie, returns the element with higher priority
  /// in the Five Elements cycle order (mu, huo, tu, jin, shui).
  public var dominantElement: Wuxing {
    let counts = elementCounts
    return Wuxing.allCases.max { a, b in
      (counts[a] ?? 0) < (counts[b] ?? 0)
    } ?? dayMasterElement
  }

  /// The Wuxing elements missing from the chart (count == 0).
  public var missingElements: [Wuxing] {
    let counts = elementCounts
    return Wuxing.allCases.filter { (counts[$0] ?? 0) == 0 }
  }

  /// The Wuxing element that the Day Master needs (supports / is generated by).
  ///
  /// In Bazi, the element that generates (sheng) the Day Master element
  /// is generally considered beneficial.
  public var beneficialElement: Wuxing {
    // The element that generates dayMasterElement
    Wuxing.allCases.first { $0.sheng == dayMasterElement } ?? dayMasterElement
  }

  /// Eight-character string representation (年月日時, stem+branch each).
  public var description: String {
    pillars.map(\.description).joined(separator: " ")
  }

  /// Full formatted display with pillar labels.
  public var formattedDescription: String {
    "年:\(nian.description) 月:\(yue.description) 日:\(ri.description) 時:\(shi.description)"
  }
}


