
import Foundation

/// The five elements used throughout Chinese philosophy.
public enum Wuxing: Int, CaseIterable, TraditionalChineseNaming, Sendable {

  case wood
  case fire
  case earth
  case metal
  case water

  // MARK: Public

  /// Heavenly stems associated with the element.
  public var tiangan: (Tiangan, Tiangan) {
    switch self {
    case .wood:
      return (.jia, .yi)
    case .fire:
      return (.bing, .ding)
    case .earth:
      return (.wu, .ji)
    case .metal:
      return (.geng, .xin)
    case .water:
      return (.ren, .kui)
    }
  }

  /// Chinese character used for the element.
  public var chineseCharacter: String {
    switch self {
    case .metal:
      return "金"
    case .wood:
      return "木"
    case .water:
      return "水"
    case .fire:
      return "火"
    case .earth:
      return "土"
    }
  }

  /// Traditional Chinese character for this element.
  public var traditionalChineseName: String { chineseCharacter }

  /// Traditional color linked to the element.
  public var colorDescription: String {
    switch self {
    case .metal:
      return "白"
    case .wood:
      return "青"
    case .water:
      return "黑"
    case .fire:
      return "赤"
    case .earth:
      return "黃"
    }
  }

  /// Traditional flavor associated with the element.
  /// 凡酸屬木入肝，苦屬火入心，甘屬土入脾，辛屬金入肺，鹹屬水入腎，此五味之義也。
  public var fiveFlavor: String {
    switch self {
    case .wood:
      return "酸"
    case .fire:
      return "苦"
    case .earth:
      return "甘"
    case .metal:
      return "辛"
    case .water:
      return "鹹"
    }
  }

  /// Element generated by this element in the generating cycle.
  public var sheng: Wuxing {
    Wuxing(rawValue: rawValue.advanced(by: 1) % Wuxing.allCases.count) ?? .metal
  }

  /// Element controlled by this element in the controlling cycle.
  public var ke: Wuxing {
    Wuxing(rawValue: rawValue.advanced(by: 2) % Wuxing.allCases.count) ?? .metal
  }

  /// Earthly branches corresponding to the element.
  public var dizhi: [Dizhi] {
    switch self {
    case .wood:
      return [.yin, .mao]
    case .fire:
      return [.si, .wu]
    case .earth:
      return [.chen, .xu, .chou, .wei]
    case .metal:
      return [.shen, .you]
    case .water:
      return [.zi, .hai]
    }
  }

  /// Direction associated with the element.
  public var fangwei: FangWei {
    switch self {
    case .metal:
      return .west
    case .earth:
      return .center
    case .fire:
      return .south
    case .wood:
      return .east
    case .water:
      return .north
    }
  }

}
